 const menus = [
     {
        m_id:1,
        m_fid:0,
        m_path:'0,',
        m_icon:'bar-chart',
        m_name:'数据分析',
        m_url:'',
     },
     {
        m_id:2,
        m_fid:0,
        m_path:'0,',
        m_icon:'gears',
        m_name:'设备管理',
        m_url:'',
     },
     {
        m_id:3,
        m_fid:0,
        m_path:'0,',
        m_icon:'pencil',
        m_name:'日志管理',
        m_url:'',
     },
     {
        m_id:4,
        m_fid:0,
        m_path:'0,',
        m_icon:'gear',
        m_name:'系统配置',
        m_url:'',
     },
     {
        m_id:5,
        m_fid:0,
        m_path:'0,',
        m_icon:'television',
        m_name:'大数据看板',
        m_url:'/bigDataVersion',
     },


     //数据分析二级
     {
        m_id:6,
        m_fid:1,
        m_path:'0,1',
        m_icon:'bar-chart',
        m_name:'实时数据',
        m_url:'/realTimeData',
     },
     {
        m_id:7,
        m_fid:1,
        m_path:'0,1',
        m_icon:'bar-chart',
        m_name:'历史数据',
        m_url:'/historicalData',
     },

    //设备管理二级
    {
        m_id:8,
        m_fid:2,
        m_path:'0,2',
        m_icon:'bar-chart',
        m_name:'树结构',
        m_url:'/treeStructure',
    },
    {
        m_id:9,
        m_fid:2,
        m_path:'0,2',
        m_icon:'bar-chart',
        m_name:'设备列表',
        m_url:'/equipmentList',
    },

    //日志管理二级
    {
        m_id:10,
        m_fid:3,
        m_path:'0,3',
        m_icon:'bar-chart',
        m_name:'设备日志',
        m_url:'/equipmentLog',
    },
    {
        m_id:11,
        m_fid:3,
        m_path:'0,3',
        m_icon:'bar-chart',
        m_name:'操作日志',
        m_url:'/operationLog',
    },

    //系统配置二级
    {
        m_id:12,
        m_fid:4,
        m_path:'0,4',
        m_icon:'bar-chart',
        m_name:'角色管理',
        m_url:'/roleManagement',
    },
    {
        m_id:13,
        m_fid:4,
        m_path:'0,4',
        m_icon:'bar-chart',
        m_name:'成员管理',
        m_url:'/membersManagement',
    },
 ]

 export default menus