var API = {}

API.organizationalStructureSearch = "/organizational_structure/search" //查询组织架构接口
API.organizationalStructureAdd    = "/organizational_structure/add" //新增组织架构接口
API.menuSearch                    = "/menu/search"//菜单表查询接口
API.menuAdd                       = "/menu/add"//菜单表新增接口
API.menuDelete                    = "/menu/delete"//菜单表删除接口
API.menuUpdate                    = "/menu/update"//菜单表更新接口
API.organizationalRoleAdd         = "/organizational_role/add"//角色表新增接口
API.userAdd                       = "/user/add"//用户表新增接口
API.userSearch                    = "/user/search"//获取用户列表
API.actionPermissionsSearch       = "/action_permissions/search"//获取接口操作列表
API.organizationalRoleSearch      = "/organizational_role/search"//获取企业角色信息
API.roleMenuMiddleSearch          = "/role_menu_middle/search"//获取角色所拥有的菜单操作
API.roleRoleMenuInfoSearch        = "/role/role_menu_info_search"//获取角色所拥有的菜单详细（带菜单信息）
API.menuActionPermissionsMiddleSearch   = "/menu_action_permissions_middle/search"//菜单操作权限表查询接口
API.menuMenuActionPermissionsInfoSearch = "/menu/menu_action_permissions_info_search"//菜单操作权限表查询接口（带接口信息）
API.systemApiAddMenuToRole        = "/systemApi/addMenuToRole"//新增菜单到角色中
API.roleMenuMiddleUpdate          = "/role_menu_middle/update"//角色菜单表（中间表）更新接口
API.organizationalRoleMiddleSearch  = "/organizational_role_middle/search"//组织架构角色表（中间表）查询接口
API.userOrganizationalMiddleSearch  = "/user_organizational_middle/search"//用户组织架构表（中间表）查询接口
API.systemApiOrganizationalToEmployee  = "/systemApi/organizationalToEmployee" //为组织架构分配员工
API.organizationalRoleUpdate      = "/organizational_role/update"//更新企业角色信息
API.bussinessApiDocsCategorySearch= "/bussiness_api_docs_category/search"//获取业务层接口分类
API.systemApiAddBussinessApiDocs  = "/systemApi/addBussinessApiDocs"//新增业务层接口
API.systemApiUpdateConfiguration  = "/systemApi/updateConfiguration"//更新原子层服务配置
API.systemApiSearchConfiguration  = "/systemApi/searchConfiguration"//获取原子层服务配置
API.systemApiRebuildConfiguration = "/systemApi/rebuildConfiguration"//重新生成原子层服务配置
API.systemApiLogin                = "/systemApi/login"//后台系统登录
API.systemApiLogin                = "/systemApi/login"//后台系统登录
API.systemAddActionPermissions    = "/systemApi/addActionPermissions"//新增原子层操作接口
API.menuActionPermissionsCategorySearch = "/menu_action_permissions_category/search"//获取接口分类信息
API.systemApiRebuildBussinessApi  = "/systemApi/rebuildBussinessApi"//重新生成接口文档配置文件
API.systemApiSearchApiDocsMenu    = "/systemApi/searchApiDocsMenu"//获取接口分类及操作接口列表
API.systemExtApiSearchApiDocsMenu    = "/systemApi/searchExtApiDocsMenu"//获取扩展接口分类及操作接口列表
API.systemApiSearchApiDocsDetail  = "/systemApi/searchApiDocsDetail"//获取接口详情信息
API.functionModuleSearch          = "/function_module/search"//获取功能模块信息
API.organizationalStructureSearch           = "/organizational_structure/search"//获取组织架构列表信息
API.systemApiOrganizationalAllocationRole   = "/systemApi/organizationalAllocationRole"//进行节点角色的分配
API.systemApiOrganizationalInheritRole      = "/systemApi/organizationalInheritRole"//为组织架构分配角色（给有继承关系的节点分配父节点的角色）
API.userAllocationRole                      = "/systemApi/userAllocationRole"//进行用户角色的分配
API.systemApiAddExtensionFunctionModule     = "/systemApi/addExtensionFunctionModule"//新增三方扩展模块
API.sysOrganizationalFunctionModuleSearch   = "/sys_organizational_function_module/search"//获取三方扩展模块
API.systemApiInstallAggregationExtension    = "/systemApi/installAggregationExtension"//安装三方扩展模块
API.systemApiUninstallAggregationExtension  = "/systemApi/unInstallAggregationExtension"//卸载三方扩展模块
API.systemApiInstallExtensionMenu    = "/extensionApi/installExtensionMenu"//安装菜单
API.systemApiUninstallExtensionMenu  = "/extensionApi/uninstallExtensionMenu"//卸载菜单
API.systemApiAddMenuToAction = "/systemApi/addMenuToAction"//为菜单分配操作
API.systemApiRemoveRole = "/systemApi/removeRole"//删除角色操作
API.systemApiRemoveMenu = "/systemApi/removeMenu"//删除菜单操作
API.systemApiRemoveNode = "/systemApi/removeNode"//删除节点操作
API.organizationalStructureUpdate = "/organizational_structure/update"//更新节点操作
API.systemApiRemoveUser = "/systemApi/removeUser"//删除用户操作
API.userUpdate = "/user/update"//更新用户信息
API.systemApiSearchAggregationApiDocsMenu = "/systemApi/searchAggregationApiDocsMenu"//查询聚合层文档列表
API.systemApiSearchAggregationApiDocsDetail = "/systemApi/searchAggregationApiDocsDetail"//查询聚合层文档详细
API.systemApiSearchAtomicApiDetail = "/systemApi/searchAtomicApiDetail"//查询原子层接口详细信息
API.systemApiUpdateActionPermissions = "/systemApi/updateActionPermissions"//更新原子层操作接口
API.systemApiRemoveActionPermissions = "/systemApi/removeActionPermissions"//删除原子层操作接口
API.systemApiRemoveActionPermissionsCategory = "/systemApi/removeActionPermissionsCategory"//删除原子层接口分类
API.menuActionPermissionsCategoryUpdate = "/menu_action_permissions_category/update"//更新原子层接口分类
API.menuActionPermissionsCategoryAdd = "/menu_action_permissions_category/add"//新增原子层接口分类
API.bussinessApiDocsSearch = "/bussiness_api_docs/search"//查询业务层接口信息
API.bussinessApiDocsDelete = "/bussiness_api_docs/delete"//删除业务层接口信息
API.systemApiSearchAggregationApiDetail = "/systemApi/searchAggregationApiDetail"//查询聚合层接口详细信息
API.systemApiUpdateAggregationApiDocs = "/systemApi/updateAggregationApiDocs"//更新聚合层接口详细信息
API.bussinessApiDocsCategoryAdd = "/bussiness_api_docs_category/add"//新增聚合层接口分类
API.systemApiRemoveAggregationApiDocsCategory = "/systemApi/removeAggregationApiDocsCategory"//删除聚合层接口分类
API.bussinessApiDocsCategoryUpdate = "/bussiness_api_docs_category/update"//更新聚合层接口分类
API.roleMenuMiddleDelete = "/role_menu_middle/delete"//删除角色下关联的菜单
API.userRoleMiddleSearch = "/user_role_middle/search"//查询用户所拥有的角色
API.functionModuleDelete = "/function_module/delete"//删除扩展模块
API.sysOrganizationalFunctionModuleUpdate = "/sys_organizational_function_module/update"//更新扩展模块
API.systemApiSearchAggregationServer = "/systemApi/searchAggregationServer"//查询聚合层服务器列表
API.sshStartServer = "/ssh/startServer"//启动聚合层服务器
API.sshStopServer = "/ssh/stopServer"//关闭聚合层服务器
API.sshRestartServer = "/ssh/restartServer"//重启聚合层服务器
API.sysAggregationServerDelete = "/sys_aggregation_server/delete"//删除聚合层服务器
API.sysAggregationServerAdd = "/sys_aggregation_server/add"//新增聚合层服务器
API.sysAggregationServerSearch = "/sys_aggregation_server/search"//查询聚合层服务器基本信息
API.sysAggregationServerUpdate = "/sys_aggregation_server/update"//更新聚合层服务器基本信息
API.sshGitPull = "/ssh/gitPull"//更新聚合层服务项目（GIT拉取操作）
API.systemApiUpdatePass = "/systemApi/updatePass" //更新用户密码
API.systemApiAddActionLog = "/systemApi/addActionLog" //添加操作日志
API.systemApiInitData = "/systemApi/initData" //初始化数据信息

export default API